### ISSUE TITLE
Finalize zenodo example entries for ranking exercise

### ISSUE THREAD

**Issue by elliewix** [Reproducible-Science-Curriculum/publication-RR-Jupyter#1]
RE: ranking exercise at the beginning of the lesson

There are currently a number of zenodo records that we identified that might make for interesting records to compare:

- https://zenodo.org/record/220887#.WHVUprYrJE4 - Simulated breed for GENMON
- https://zenodo.org/record/193080#.WHVWI7YrJE4 - Raw data for a manuscript. Gives manuscript title.
- https://zenodo.org/record/215975#.WHVVCLYrIxF 
- https://zenodo.org/record/193025#.WHVVrrYrIxE 
- https://zenodo.org/record/158943#.WHVXZbYrIxG - data, jupyter notebook, video, and readme file for a paper (http://iopscience.iop.org/article/10.1088/0143-0807/38/1/015005/meta#footnotes)

At a minimum we need to pick this down to just three records for comparison prompting.  

But better would be to have a few sets of records that are slightly more apples/apples comparisons.  E.g. stuff with code and data, just data packages, just code packages, posters, etc?  Perhaps centered around specific domains, e.g. earth science, social science, entomology, etc.  Having multiple sets of groups allows instructors to pick relevant items for their group, if that would be valuable.

These don't all have to be from Zenodo, but would like entries from each set to all be on the same platform.  This means that domain specific records could be from domain specific repositories that the learners would emote with.

**Comment by hlapp** [comment]
It seems like the following give a reasonable gradual step up from poor to best:

* MS Salmanpour. (2016). Data set [Data set]. Zenodo. http://doi.org/10.5281/zenodo.193025
    - Meaningless title, no description, no README
    - no links to anything
    - proprietary file format
* Solange Duruz. (2016). Simulated breed for GENMON [Data set]. Zenodo. http://doi.org/10.5281/zenodo.220887
    - Title with useful information. No description, no README
    - no links to anything
    - open reusable data format
* Zichen Wang, Avi Ma'ayan. Zika-RNAseq-Pipeline v0.1. Zenodo; 2016. http://doi.org/10.5281/zenodo.56311
    - Informative title and short description. README file.
    - Links to Github, from README to paper and Zenodo archive, from paper to Github and Zenodo archive
    - Everything in open reusable formats
