### ISSUE TITLE
template all the things

### ISSUE THREAD

**Issue by elliewix** [Reproducible-Science-Curriculum/publication-RR-Jupyter#10]
We've got stuff in MD and ipynb, so things will need to be moved over to the final format.

**Comment by raynamharris** [comment]
I think it will be better to keep the documentation episode as a markdown file since it contains no python code. However, if you would like to convert it to .ipynb, go ahead and create the pull request.

**Comment by hlapp** [comment]
I've now converted the iPython format documents to Markdown (as per #23). It still needs to be converted to the Data Carpentry lesson template, but I think that should be a separate issue, so I'll close this out.
