### ISSUE TITLE
Create exercise for evaluating project README files

### ISSUE THREAD

**Issue by raynamharris** [Reproducible-Science-Curriculum/publication-RR-Jupyter#12]
Elaborate on this exercise for evaluating README.md files in the documentation episode
https://github.com/Reproducible-Science-Curriculum/publication-RR-Jupyter/blob/master/documentation.md#readme-file

**Comment by hlapp** [comment]
Can this be considered now with the changes to [documentation.md](https://github.com/Reproducible-Science-Curriculum/publication-RR-Jupyter/blob/master/documentation.md#readme-file) from #20 and #22?

**Comment by raynamharris** [comment]
Yes, I think we can close this now @hlapp
