### ISSUE TITLE
teaching this lesson on March 8th

### ISSUE THREAD

**Issue by tracykteal** [Reproducible-Science-Curriculum/publication-RR-Jupyter#16]
I've committed to teach this lesson as a pilot on March 8th at UC Davis

**Comment by elliewix** [comment]
Excellent!

**Comment by choldgraf** [comment]
![image](http://cultofthepartyparrot.com/parrots/parrot.gif)

**Comment by raynamharris** [comment]
@tracykteal let us know if you have specific questions or concerns regarding the material or if you want to have a debrief afterwards. I'm curious to see how this goes.

**Comment by hlapp** [comment]
Me too! I'll be teaching this next week. We should debrief!

**Comment by hlapp** [comment]
This pilot was canceled.
