### ISSUE TITLE
Use Jupyter Notebook or simple Markdown for lessons?

### ISSUE THREAD

**Issue by hlapp** [Reproducible-Science-Curriculum/publication-RR-Jupyter#23]
The Record-level Metadata and the Publication sections of the lesson are presently in iPython Notebook format, not Markdown, even though at present they don't contain materials that would call for the capabilities of an iPython/Jupyter notebook.

In contrast, the Exporting the Notebook and the Documentation sections are in plain Markdown format.

I'm not strongly wedded to using either format, but I think the format should be consistent, and in general should be what's needed. I don't see exercises in the planning stage (and am not planning any myself) that would require or benefit from an interactive executable iPython notebook, so I'm inclined to convert all of them into Markdown.

Comments, objections, or alternative suggestions?

**Comment by elliewix** [comment]
The items written in Jupyter Notebooks were strictly because that's what I was comfortable writing in and I thought there had been discussions of everything going into notebooks.  I have no issue with them being migrated into markdown.
