### ISSUE TITLE
typo at lesson 2

### ISSUE THREAD

**Issue by alex-bender** [Reproducible-Science-Curriculum/publication-RR-Jupyter#49]
Hello! Thanks for that content. It is really great. There is a typo in the command at 
Lesson 2 file exporting_the_notebook.md,
Section Introduction.
Command `nbocnvert` shoulb be nbconvert I guess.
Thanks!

**Comment by hlapp** [comment]
True! @alex-bender do you want to submit a pull request?

**Comment by alex-bender** [comment]
I've tried to before opening the issue, but i'm on my phone and it's wonky. Old browser, you know.

**Comment by hlapp** [comment]
Fixed in #50.
