### ISSUE TITLE
open access information

### ISSUE THREAD

**Issue by elliewix** [Reproducible-Science-Curriculum/publication-RR-Jupyter#6]
Also placing in some super stub information.  Needs to be reviewed/torn apart by someone who knows more than I.

**Comment by hlapp** [comment]
See comment in #4 - I suggest this has become obsolete. OK to close?

**Comment by hlapp** [comment]
I'll close out this one but change #4 to the question as to whether Open Access should be included as well (as it contains the thread) and leave that open.
