### ISSUE TITLE
software licenses

### ISSUE THREAD

**Issue by elliewix** [Reproducible-Science-Curriculum/publication-RR-Jupyter#8]
I'm adding stub information, and someone with more expertise should flesh out that information.  Just be sure to keep an unbiased voice. These selections are meant to be by the authors and we should respect their desires, even if we (of the open source communities) might disagree with them.

**Comment by hlapp** [comment]
The following articles should be useful: https://paperpile.com/shared/gjMNOu

**Comment by hlapp** [comment]
I think #26 once merged should address this?
